Traceback (most recent call last):
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
analyzer = ThresholdAnalyzer()
threshold = ThresholdTriangle()
fig = analyzer.analyze(images=images)

glue("threshold_triangle", fig)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 3[0m
[1;32m      1[0m analyzer [38;5;241m=[39m ThresholdAnalyzer()
[1;32m      2[0m threshold [38;5;241m=[39m ThresholdTriangle()
[0;32m----> 3[0m fig [38;5;241m=[39m [43manalyzer[49m[38;5;241;43m.[39;49m[43manalyze[49m[43m([49m[43mimages[49m[38;5;241;43m=[39;49m[43mimages[49m[43m)[49m
[1;32m      5[0m glue([38;5;124m"[39m[38;5;124mthreshold_triangle[39m[38;5;124m"[39m, fig)

[0;31mTypeError[0m: ThresholdAnalyzer.analyze() missing 1 required positional argument: 'threshold'
TypeError: ThresholdAnalyzer.analyze() missing 1 required positional argument: 'threshold'

