Traceback (most recent call last):
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, (ax1,ax2) = plt.subplots(figsize=(12,4), nrows=1, ncols=2)
dataCBIS = [175,501,539,331]
dataUS = [10,40,40,10]
keys = ['Almost Entirely Fatty','Scattered Areas of \nFibroglandular Density', 'Heterogeneously Dense', 'Extremely Dense']
palette_color = sns.color_palette('Blues_r')
ax1.pie(dataUS, labels=keys, colors=palette_color, autopct='%.0f%%', ax=ax1)
ax2 = plt.pie(dataCBIS, labels=keys, colors=palette_color, autopct='%.0f%%', ax=ax2)
ax1.set_title("Breast Density in the U.S.")
ax1.set_title("Breast Density in CBIS-DDSM.")
#plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[7], line 6[0m
[1;32m      4[0m keys [38;5;241m=[39m [[38;5;124m'[39m[38;5;124mAlmost Entirely Fatty[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mScattered Areas of [39m[38;5;130;01m\n[39;00m[38;5;124mFibroglandular Density[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mHeterogeneously Dense[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mExtremely Dense[39m[38;5;124m'[39m]
[1;32m      5[0m palette_color [38;5;241m=[39m sns[38;5;241m.[39mcolor_palette([38;5;124m'[39m[38;5;124mBlues_r[39m[38;5;124m'[39m)
[0;32m----> 6[0m [43max1[49m[38;5;241;43m.[39;49m[43mpie[49m[43m([49m[43mdataUS[49m[43m,[49m[43m [49m[43mlabels[49m[38;5;241;43m=[39;49m[43mkeys[49m[43m,[49m[43m [49m[43mcolors[49m[38;5;241;43m=[39;49m[43mpalette_color[49m[43m,[49m[43m [49m[43mautopct[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;132;43;01m%.0f[39;49;00m[38;5;132;43;01m%%[39;49;00m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43max[49m[38;5;241;43m=[39;49m[43max1[49m[43m)[49m
[1;32m      7[0m ax2 [38;5;241m=[39m plt[38;5;241m.[39mpie(dataCBIS, labels[38;5;241m=[39mkeys, colors[38;5;241m=[39mpalette_color, autopct[38;5;241m=[39m[38;5;124m'[39m[38;5;132;01m%.0f[39;00m[38;5;132;01m%%[39;00m[38;5;124m'[39m, ax[38;5;241m=[39max2)
[1;32m      8[0m ax1[38;5;241m.[39mset_title([38;5;124m"[39m[38;5;124mBreast Density in the U.S.[39m[38;5;124m"[39m)

[0;31mTypeError[0m: Axes.pie() got multiple values for argument 'ax'

